### ISSUE TITLE
NameOfHolder and NFC Screen being null Issues

### ISSUE THREAD

**Issue by nabaanahith** [idpass/smartscanner-core#68]
## Current Behaviour

the name not display properly
 
## Expected Behaviour

display in readable way without any empty values

**Comment by rjmangubat23** [comment]
Based on Firebase crash logs this issue may be due to crashes concerning the following:

- `MrzInfo.java` where mrz is sometimes null when passed causing  RuntimeException/EOFException
![image](https://user-images.githubusercontent.com/11598375/119453063-9db48000-bd69-11eb-97b8-1299ebf25bd0.png)

- `NFCFragment.kt` is having a NullPointerException
![image](https://user-images.githubusercontent.com/11598375/119452884-7067d200-bd69-11eb-9787-1f1db0908ad8.png)
